<a href="https://colab.research.google.com/github/bhardwaj0027/Deep-Learning-CSL312/blob/main/Experiment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(0,10,1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a2 = np.random.randint(25,size=(3,4))
a2

array([[ 9, 21,  4,  6],
       [ 2,  6, 12,  2],
       [15,  0,  2,  0]])

In [4]:
a2.reshape([4,3])

array([[ 9, 21,  4],
       [ 6,  2,  6],
       [12,  2, 15],
       [ 0,  2,  0]])

In [5]:
"'3rd element from 1D array'"
a[2]

2

In [6]:
"'accessing last 2 columns of a 2D array'"
a2[:,-2:]

array([[ 4,  6],
       [12,  2],
       [ 2,  0]])

In [7]:
"'3x3 matrix ranging 0,8'"
m = np.arange(0, 9).reshape([3,3])
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
"'diagnal element of the matrix'"
np.diagonal(m)

array([0, 4, 8])

In [9]:
np.product(a2)

0

In [10]:
print(np.mean(a2))
print(np.median(a2))

6.583333333333333
5.0


In [12]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.multiply(array1, array2)
print(result)

[ 4 10 18]
